# config/packages/monolog.yaml
monolog:
  channels:
    - deprecation # Canal pour les dépréciations
    - user_activity # Canal pour les actions utilisateur

  handlers:
    # Handler principal pour le mode dev et prod
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]

    # Handler pour les logs de dépréciations
    deprecation:
      type: stream
      channels: [deprecation]
      path: "%kernel.logs_dir%/deprecation.log"

    # Handler pour les actions utilisateur
    user_activity:
      type: stream
      path: "%kernel.logs_dir%/user_activity.log"
      level: info
      channels: ["user_activity"]

    # Handler pour l'affichage dans la console en dev
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/dev.log"
        level: debug
        channels: ["!event"]
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        channels: ["!event"]
      nested:
        type: stream
        path: "%kernel.logs_dir%/test.log"
        level: debug

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      nested:
        type: stream
        path: php://stderr
        level: error
        formatter: monolog.formatter.json

      # Handler pour les logs de dépréciations en prod
      deprecation:
        type: stream
        channels: [deprecation]
        path: php://stderr
        formatter: monolog.formatter.json

      # Handler pour les logs utilisateur en prod
      user_activity:
        type: stream
        path: "%kernel.logs_dir%/user_activity.log"
        level: info
        channels: ["user_activity"]
